version: '3'
services:
  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile-eureka.txt
    image: eureka-server-image
    ports:
      - "8761:8761"
    networks:
      - my-network
    volumes:
      - eureka-data:/app/eureka

  products-service:
    build:
      context: .
      dockerfile: products/Dockerfile-products.txt
    image: products-image
    ports:
      - "8001:8001"
    networks:
      - my-network
    volumes:
      - products-data:/app/products
    depends_on:
      - eureka-server

networks:
  my-network:

volumes:
  eureka-data:
  products-data:
